jobs:
  integrationTests:
    if: "github.repository == 'spring-cloud/spring-cloud-gcp' &&\n(\n  github.event_name\
      \ == 'push' ||\n  github.event_name == 'schedule'\n)\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Setup gcloud
      uses: google-github-actions/setup-gcloud@master
      with:
        export_default_credentials: true
        project_id: spring-cloud-gcp-ci
        service_account_key: ${{ secrets.SPRING_CLOUD_GCP_CI_SA_KEY }}
        version: latest
    - continue-on-error: true
      name: Install pubsub-emulator
      run: "gcloud components install pubsub-emulator beta && \\\n  gcloud components\
        \ update\n"
    - continue-on-error: true
      id: install1
      name: Mvn install
      run: "./mvnw \\\n  --batch-mode \\\n  --threads 1.5C \\\n  --define maven.test.skip=true\
        \ \\\n  --define maven.javadoc.skip=true \\\n  install\n"
    - continue-on-error: true
      id: install2
      if: steps.install1.outcome == 'failure'
      name: Retry Mvn install
      run: "./mvnw \\\n  --batch-mode \\\n  --threads 1.5C \\\n  --define maven.test.skip=true\
        \ \\\n  --define maven.javadoc.skip=true \\\n  install\n"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Wait our turn for running integration tests
      uses: softprops/turnstyle@v1
      with:
        continue-after-seconds: 1200
    - continue-on-error: true
      env:
        GOOGLE_CLOUD_PROJECT: spring-cloud-gcp-ci
      id: intTests1
      name: Integration Tests
      run: "./mvnw \\\n  --batch-mode \\\n  --define maven.javadoc.skip=true \\\n\
        \    -Dit.pubsub-emulator=true  \\\n    -Dit.spanner=true  \\\n    -Dit.storage=true\
        \  \\\n    -Dit.config=true  \\\n    -Dit.pubsub=true  \\\n    -Dit.logging=true\
        \ \\\n    -Dit.cloudsql=true  \\\n    -Dit.datastore=true  \\\n    -Dit.trace=true\
        \  \\\n    -Dit.kotlin=true  \\\n    -Dit.vision=true  \\\n    -Dit.firestore=true\
        \  \\\n    -Dit.bigquery=true  \\\n    -Dit.secretmanager=true  \\\n    -Dit.metrics=true\
        \ \\\n    -Dspring.cloud.gcp.sql.instance-connection-name=spring-cloud-gcp-ci:us-central1:testmysql\
        \ \\\n    -Dspring.cloud.gcp.sql.database-name=code_samples_test_db \\\n \
        \   -Dspring.datasource.password=test \\\n    -Dgcs-resource-test-bucket=gcp-storage-resource-bucket-sample\
        \ \\\n    -Dgcs-read-bucket=gcp-storage-bucket-sample-input \\\n    -Dgcs-write-bucket=gcp-storage-bucket-sample-output\
        \ \\\n    -Dgcs-local-directory=/tmp/gcp_integration_tests/integration_storage_sample\
        \ \\\n  verify\n"
    - continue-on-error: true
      env:
        GOOGLE_CLOUD_PROJECT: spring-cloud-gcp-ci
      id: intTests2
      if: steps.intTests1.outcome == 'failure'
      name: Retry Integration Tests on Failure
      run: "./mvnw \\\n  --batch-mode \\\n  --define maven.javadoc.skip=true \\\n\
        \    -Dit.pubsub-emulator=true  \\\n    -Dit.spanner=true  \\\n    -Dit.storage=true\
        \  \\\n    -Dit.config=true  \\\n    -Dit.pubsub=true  \\\n    -Dit.logging=true\
        \ \\\n    -Dit.cloudsql=true  \\\n    -Dit.datastore=true  \\\n    -Dit.trace=true\
        \  \\\n    -Dit.kotlin=true  \\\n    -Dit.vision=true  \\\n    -Dit.firestore=true\
        \  \\\n    -Dit.bigquery=true  \\\n    -Dit.secretmanager=true  \\\n    -Dit.metrics=true\
        \ \\\n    -Dspring.cloud.gcp.sql.instance-connection-name=spring-cloud-gcp-ci:us-central1:testmysql\
        \ \\\n    -Dspring.cloud.gcp.sql.database-name=code_samples_test_db \\\n \
        \   -Dspring.datasource.password=test \\\n    -Dgcs-resource-test-bucket=gcp-storage-resource-bucket-sample\
        \ \\\n    -Dgcs-read-bucket=gcp-storage-bucket-sample-input \\\n    -Dgcs-write-bucket=gcp-storage-bucket-sample-output\
        \ \\\n    -Dgcs-local-directory=/tmp/gcp_integration_tests/integration_storage_sample\
        \ \\\n  verify\n"
    - continue-on-error: true
      if: always()
      name: Archive logs
      uses: actions/upload-artifact@v2
      with:
        name: Integration Test Logs
        path: '**/target/failsafe-reports/*'
    strategy:
      fail-fast: false
name: Integration Tests
on:
  repository_dispatch:
    types: trigger-ga___integrationTests.yml
