jobs:
  unitTest:
    if: "( github.event_name == 'push' ||\n  github.event.pull_request.head.repo.full_name\
      \ != 'spring-cloud/spring-cloud-gcp' )\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      id: unitTest1
      name: Unit Tests
      run: "./mvnw \\\n  --batch-mode \\\n  --fail-at-end \\\n  --threads 1.5C \\\n\
        \  test\n"
    - continue-on-error: true
      id: unitTest2
      if: steps.unitTest1.outcome == 'failure'
      name: Retry Unit Tests on Failure
      run: "./mvnw \\\n  --batch-mode \\\n  --fail-at-end \\\n  --threads 1.5C \\\n\
        \  test\n"
    - continue-on-error: true
      if: always()
      name: Archive logs
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Logs - Java ${{ matrix.java }}
        path: '**/target/surefire-reports/*'
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
        - 15
name: Unit Tests
on:
  repository_dispatch:
    types: trigger-ga___unitTests.yml
